"""Python layer map for harness lint."""

from __future__ import annotations

MAX_PYTHON_LINES = 320
PYTHON_DISCOVERY_ROOTS = ("intentos", "tests")
EXPECTED_LAYERS = {
    "intentos/__init__.py",
    "intentos/activity.py",
    "intentos/classifier.py",
    "intentos/classifier_context.py",
    "intentos/reporting.py",
    "intentos/activity_cli.py",
    "intentos/activity_evaluate.py",
    "intentos/beta/__init__.py",
    "intentos/beta/daily_loop.py",
    "intentos/beta/daily_state.py",
    "intentos/beta/db_health.py",
    "intentos/beta/extension.py",
    "intentos/beta/focus_rescue.py",
    "intentos/beta/http_client.py",
    "intentos/beta/keys.py",
    "intentos/beta/loop_coach.py",
    "intentos/beta/native_recorder.py",
    "intentos/beta/permissions.py",
    "intentos/beta/recorder.py",
    "intentos/beta/review.py",
    "intentos/beta/schema.py",
    "intentos/beta/service.py",
    "intentos/beta/service_helpers.py",
    "intentos/beta/service_security.py",
    "intentos/beta/setup_diagnostics.py",
    "intentos/beta/setup_flow.py",
    "intentos/beta/state.py",
    "intentos/beta/store.py",
    "intentos/beta/weekly_patterns.py",
    "intentos/beta_cli.py",
    "intentos/capture/__init__.py",
    "intentos/capture/browser.py",
    "intentos/capture/core.py",
    "intentos/capture/jsonl.py",
    "intentos/capture/live.py",
    "intentos/capture/live_cli.py",
    "intentos/capture/macos.py",
    "intentos/capture/privacy.py",
    "intentos/capture/report_cli.py",
    "intentos/capture/session.py",
    "intentos/capture_cli.py",
    "intentos/capture_replay.py",
    "intentos/youtube.py",
    "intentos/cli.py",
    "intentos/evaluate.py",
    "tests/test_activity_classification.py",
    "tests/beta_service_harness.py",
    "tests/test_beta_activation.py",
    "tests/test_beta_api_security.py",
    "tests/test_beta_corrections.py",
    "tests/test_beta_daily_loop.py",
    "tests/test_beta_delete_data.py",
    "tests/test_beta_extension.py",
    "tests/test_beta_menu_app.py",
    "tests/test_beta_native_recorder.py",
    "tests/test_beta_onboarding_api.py",
    "tests/test_beta_permissions.py",
    "tests/test_beta_service.py",
    "tests/test_beta_store.py",
    "tests/test_beta_validation_runtime.py",
    "tests/test_capture_browser.py",
    "tests/test_capture_cli.py",
    "tests/test_capture_core.py",
    "tests/test_capture_live.py",
    "tests/test_capture_macos.py",
    "tests/test_capture_privacy.py",
    "tests/test_capture_replay.py",
    "tests/test_capture_session.py",
    "tests/test_harness_completion.py",
    "tests/test_render_ui_check.py",
    "tests/test_youtube_mvp.py",
}
ALLOWED_IMPORTS = {
    "intentos/__init__.py": set(),
    "intentos/cli.py": {"intentos.youtube"},
    "intentos/evaluate.py": {"intentos.youtube"},
    "intentos/classifier.py": {"intentos.activity", "intentos.classifier_context"},
    "intentos/classifier_context.py": {"intentos.activity"},
    "intentos/reporting.py": {
        "intentos.activity",
        "intentos.classifier",
        "intentos.youtube",
    },
    "intentos/activity_cli.py": {"intentos.activity", "intentos.reporting"},
    "intentos/activity_evaluate.py": {"intentos.activity", "intentos.classifier"},
    "intentos/beta/__init__.py": set(),
    "intentos/beta/daily_loop.py": {
        "intentos.beta",
        "intentos.youtube",
    },
    "intentos/beta/daily_state.py": {
        "intentos.beta",
    },
    "intentos/beta/db_health.py": set(),
    "intentos/beta/extension.py": {
        "intentos.activity",
        "intentos.capture.browser",
        "intentos.capture.privacy",
    },
    "intentos/beta/focus_rescue.py": {
        "intentos.beta",
        "intentos.youtube",
    },
    "intentos/beta/http_client.py": {
        "intentos.beta.service_security",
    },
    "intentos/beta/keys.py": set(),
    "intentos/beta/loop_coach.py": {
        "intentos.youtube",
    },
    "intentos/beta/native_recorder.py": {
        "intentos.activity",
        "intentos.beta",
        "intentos.capture.live",
        "intentos.capture.macos",
    },
    "intentos/beta/permissions.py": {
        "intentos.beta",
        "intentos.capture",
    },
    "intentos/beta/recorder.py": {
        "intentos.activity",
        "intentos.beta",
        "intentos.capture.core",
        "intentos.capture.session",
    },
    "intentos/beta/review.py": {
        "intentos.activity",
        "intentos.beta",
        "intentos.beta.keys",
        "intentos.classifier",
        "intentos.reporting",
        "intentos.youtube",
    },
    "intentos/beta/schema.py": set(),
    "intentos/beta/service.py": {
        "intentos.beta",
        "intentos.beta.extension",
        "intentos.beta.service_helpers",
        "intentos.capture.privacy",
    },
    "intentos/beta/service_helpers.py": set(),
    "intentos/beta/service_security.py": set(),
    "intentos/beta/setup_diagnostics.py": {
        "intentos.beta",
    },
    "intentos/beta/setup_flow.py": {
        "intentos.beta",
    },
    "intentos/beta/state.py": {
        "intentos.beta",
    },
    "intentos/beta/store.py": {
        "intentos.beta.db_health",
        "intentos.beta.keys",
        "intentos.beta.schema",
        "intentos.beta",
        "intentos.activity",
        "intentos.classifier",
        "intentos.reporting",
    },
    "intentos/beta/weekly_patterns.py": {
        "intentos.beta",
        "intentos.youtube",
    },
    "intentos/beta_cli.py": {
        "intentos.beta",
        "intentos.beta.extension",
        "intentos.beta.service",
        "intentos.capture.privacy",
    },
    "intentos/capture/__init__.py": {
        "intentos.capture.core",
        "intentos.capture.jsonl",
    },
    "intentos/capture/browser.py": set(),
    "intentos/capture/core.py": {"intentos.activity"},
    "intentos/capture/jsonl.py": {"intentos.activity"},
    "intentos/capture/live.py": {
        "intentos.activity",
        "intentos.capture.browser",
        "intentos.capture.core",
        "intentos.capture.jsonl",
        "intentos.capture.macos",
        "intentos.capture.privacy",
        "intentos.capture.session",
        "intentos.capture_replay",
    },
    "intentos/capture/live_cli.py": {
        "intentos.capture.live",
        "intentos.capture.macos",
    },
    "intentos/capture/macos.py": {"intentos.capture.core"},
    "intentos/capture/privacy.py": set(),
    "intentos/capture/report_cli.py": set(),
    "intentos/capture/session.py": {
        "intentos.activity",
        "intentos.capture.browser",
        "intentos.capture.core",
        "intentos.capture.macos",
    },
    "intentos/capture_replay.py": {"intentos.capture.jsonl", "intentos.reporting"},
    "intentos/capture_cli.py": {
        "intentos.capture.browser",
        "intentos.capture.core",
        "intentos.capture.jsonl",
        "intentos.capture.privacy",
        "intentos.capture.live_cli",
        "intentos.capture.macos",
        "intentos.capture.report_cli",
        "intentos.capture.session",
        "intentos.capture_replay",
    },
    "tests/test_activity_classification.py": {
        "intentos.activity",
        "intentos.activity_evaluate",
        "intentos.classifier",
        "intentos.reporting",
    },
    "tests/beta_service_harness.py": {
        "intentos.beta",
        "intentos.beta.http_client",
        "intentos.beta.service",
    },
    "tests/test_beta_activation.py": {
        "intentos.beta",
    },
    "tests/test_beta_api_security.py": set(),
    "tests/test_beta_corrections.py": set(),
    "tests/test_beta_daily_loop.py": {
        "intentos.activity",
        "intentos.beta",
    },
    "tests/test_beta_delete_data.py": {
        "intentos.beta",
    },
    "tests/test_beta_extension.py": {
        "intentos.beta.extension",
        "intentos.capture.privacy",
    },
    "tests/test_beta_menu_app.py": set(),
    "tests/test_beta_native_recorder.py": {
        "intentos.activity",
        "intentos.beta",
    },
    "tests/test_beta_permissions.py": {
        "intentos.beta",
    },
    "tests/test_beta_onboarding_api.py": set(),
    "tests/test_beta_service.py": set(),
    "tests/test_beta_store.py": {
        "intentos.activity",
        "intentos.beta",
    },
    "tests/test_beta_validation_runtime.py": set(),
    "tests/test_capture_browser.py": {"intentos.capture.browser"},
    "tests/test_capture_cli.py": {
        "intentos.capture.browser",
        "intentos.capture.macos",
        "intentos.capture_cli",
    },
    "tests/test_capture_core.py": {
        "intentos.capture.core",
        "intentos.capture.jsonl",
    },
    "tests/test_capture_live.py": {
        "intentos.capture.browser",
        "intentos.capture.jsonl",
        "intentos.capture.live",
        "intentos.capture.macos",
    },
    "tests/test_capture_macos.py": {"intentos.capture.macos"},
    "tests/test_capture_privacy.py": {"intentos.capture.privacy"},
    "tests/test_capture_replay.py": {
        "intentos.capture_cli",
        "intentos.capture_replay",
    },
    "tests/test_capture_session.py": {
        "intentos.capture.browser",
        "intentos.capture.core",
        "intentos.capture.jsonl",
        "intentos.capture.macos",
        "intentos.capture.session",
        "intentos.capture_cli",
        "intentos.capture_replay",
    },
    "tests/test_harness_completion.py": {
        "intentos.activity",
        "intentos.beta",
    },
    "tests/test_render_ui_check.py": set(),
    "tests/test_youtube_mvp.py": {"intentos.youtube"},
}
